name: CI

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Yarn install, build and deploy
        run: |
          yarn install
          yarn run build
          yarn run deploy
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: packages/client/public
